version: '3'
services:
  redis:
    image: redis
    restart: always
    container_name: docker_redis
    network_mode: host
    volumes:
      - ./datadir:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.6
    container_name: docker_mysql
    network_mode: host
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'testdb'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - 3306:3306
    volumes:
      - ../scripts/sql:/docker-entrypoint-initdb.d/
  myapp:
    image: myapp:0.2.2
    container_name: docker_myapp
    network_mode: host
    restart: always
    command: npm start
    depends_on:
      - mysql
      - redis
    build: ./
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER_NAME: 'root'
      DATABASE_USER_PASSWORD: 'root123'
      DATABASE_DB_NAME: 'testdb'
      DATABASE_PORT: '3306'
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    ports:
      - 8082:8082